### ISSUE TITLE
[Backend]: Complete Implementation of Sequelize with MySQL

### ISSUE THREAD

**Issue by Mayank0255** [Mayank0255/Stackoverflow-Clone-Backend#2]
Convert the backend API models by using Sequelize instead of raw MySQL queries

- [x] #4  
- [x] #3

**Comment by fabioalmeida100** [comment]
> @fabioalmeida100 yesterday I have split up the front-end and back-end code in two repositories, the front-end code remains here, and the the backend code is being shifted to [Stackoverflow-Clone-Backend](https://github.com/Mayank0255/Stackoverflow-Clone-Backend)
> As the project is growing and more developers are joining in, the management is getting tougher and the number of issues they are facing are also increasing, this is the reason this has been done. It will also us to make the code quality even better and allow adding features more streamlined.
> 
> So, this issue and the 2 other sub-issues are more suitable to the backend repo, that's why I will be creating these same issues over there and closing them here. I request you to comment on the issues over there and kindly shift your code accordingly.

Hello @Mayank0255  No problem! I will refresh the project in my computer. It will be good we have unit test or integration test in back-end, mainly, because the project is growing... Bugs, and some problems, can be more frequency with the project growing.

I suggest two approaches at this moment, in addition to the project division:

- Implementation of the unit test with Jest (keeping coverage in 60% for first time, and in a second time 90%)
- Implementation the integration test with supertest library (for test the endpoints and check true response with all back-end code in action)

**Comment by Mayank0255** [comment]
@fabioalmeida100 

This seems like a good idea, though I haven't done this before so I am a beginner with this. Can you recommend me some good resources from which I can know about it?

And have you heard of something like __Travis-CI__?

**Comment by fabioalmeida100** [comment]
Open PR: https://github.com/Mayank0255/Stackoverflow-Clone-Backend/pull/10
